SAVE_ADVERSARIAL_EXAMPLES = True
SAVE_PERTURBATIONS = True
IMAGE_SIZE = 256

GENERATE_ADVERSARIAL_EXAMPLES_DCT = False
BLOCK_SIZE_DCT = 8
FACTOR_DCT = 0.3
MASK_WATER_MARK_DC = False
MASK_WATER_MARK_EDGES = True
MASK_HOST_DC = True
MASK_HOST_EDGES = True

SAVE_DCT_HOST_IMAGE_DC_INFO = True
SAVE_DCT_HOST_IMAGE_EDGE_INFO = True
SAVE_STEGO_IMAGE = True
FILENAME_DCT_HOST_IMAGE_DC_INFO = 'DCT_Host_Image_DC_Info'
FILENAME_DCT_HOST_IMAGE_EDGE_INFO = 'DCT_Host_Image_Edge_Info'
FILENAME_DCT_STEGO_IMAGE = 'DCT_Stego_Image'

GENERATE_ADVERSARIAL_EXAMPLES_FFT = False
FACTOR_FFT = 0.9
MAGNITUDE_HOST = True
PHASE_HOST = True
MAGNITUDE_WATER_MARK = False
PHASE_WATER_MARK = True
FILENAME_FFT_STEGO_IMAGE = 'FFT_Stego_Image'

GENERATE_ADVERSARIAL_EXAMPLES_DWT = True
FACTOR_DWT = 0.9
WAVELET_FAMILY = 'haar'
SAVE_HOST_IMAGE_DWT_INFO = True
SAVE_STEGO_IMAGE = True
FILENAME_HOST_IMAGE_DWT_INFO = 'Host_Image_DWT_Info'
FILENAME_WATERMARK_IMAGE_DWT_INFO = 'Watermark_Image_DWT_Info'
FILENAME_DWT_STEGO_IMAGE = 'DWT_Stego_Image'

WATERMARK_IMAGE = r'C:\Users\DELL\OneDrive\Documents\TDA\data\watermark\watermark1.jpeg'
HOST_IMAGE_DIR = r'C:\Users\DELL\OneDrive\Documents\TDA\data\host_images'
ADVERSARIAL_EXAMPLES_DIR = r'C:\Users\DELL\OneDrive\Documents\TDA\output\adversarial_examples'
PERTURBATIONS_DIR = r'C:\Users\DELL\OneDrive\Documents\TDA\output\perturbations'